In [1]:
import numpy as np

In [6]:
x = np.array([[1, 2], [3, 4]])
print np.pad(x, ((0, 0), (0, 2)), 'constant', constant_values=0)

[[1 2 0 0]
 [3 4 0 0]]


In [11]:
def pad_with(array, value=0):
    return np.pad(array, ((0, 0), (0, 2)), 'constant', constant_values=value)

In [68]:
def pad_with2(array, value=0):
    x = np.zeros((2, 5))
    x[:array.shape[0], :array.shape[1]] = array
    return x
print pad_with2(e[:,1:])

[[ 20.   0.   0.   0.   0.]
 [400.   0.   0.   0.   0.]]


In [83]:
s = pad_with2(np.array([[1, 3, 2], [1, 1, 3]]))
e = np.array([[10, 10, 10], [200, 100, 300]])
a = np.stack((s * pad_with2(e), s * pad_with2(e[:,1:])), axis=1)
print a
print a[0]
print np.unravel_index(np.argmax(a[0]), a[0].shape)

[[[ 10.  30.  20.   0.   0.]
  [ 10.  30.   0.   0.   0.]]

 [[200. 100. 900.   0.   0.]
  [100. 300.   0.   0.   0.]]]
[[10. 30. 20.  0.  0.]
 [10. 30.  0.  0.  0.]]
(0, 1)


In [84]:
x = np.asarray([np.unravel_index(np.argmax(a[i]), a[i].shape) for i in xrange(a.shape[0])])
print x
print x[...,1]
print x[...,1] + x[...,0]

[[0 1]
 [0 2]]
[1 2]
[1 2]


In [87]:
x = np.array([[1, 2, 3], [3, 4, 5]])
print x
np.random.shuffle(x.T)
print x

[[1 2 3]
 [3 4 5]]
[[3 2 1]
 [5 4 3]]
