In [50]:
import tensorflow as tf
import numpy as np

In [3]:
x = tf.placeholder(tf.int32, shape=[None, 2])
y, z = tf.split(x, 2, axis=1)

with tf.Session() as sess:
    print(sess.run(y, {x: [[1, 2], [3, 4]]}))
    print(sess.run(z, {x: [[1, 2], [3, 4]]}))

[[1]
 [3]]
[[2]
 [4]]


In [13]:
x = tf.placeholder(tf.int32, shape=[None, 2])
y = tf.placeholder(tf.int32, shape=[None, 2])
with tf.Session() as sess:
    print(sess.run(tf.concat((x, y), axis=1), {x: [[1, 2], [3, 4]], y: [[5, 6], [7, 8]]}))

[[1 2 5 6]
 [3 4 7 8]]


In [11]:
x = tf.placeholder(tf.int32, shape=[None, 4])

y, z = tf.split(x, 2, axis=1)
with tf.Session() as sess:
    print(sess.run(y, {x: [[1, 2, 5, 6], [3, 4, 7, 8]]}))
    print(sess.run(z, {x: [[1, 2, 5, 6], [3, 4, 7, 8]]}))
    print sess.run(y + z, {x: [[1, 2, 5, 6], [3, 4, 7, 8]]})
    print sess.run((y + z) / 2, {x: [[1, 2, 5, 6], [3, 4, 7, 8]]})
    print sess.run(tf.maximum(y, z), {x: [[1, 2, 5, 6], [3, 4, 7, 8]]})

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]
[[ 6  8]
 [10 12]]
[[3 4]
 [5 6]]
[[5 6]
 [7 8]]


In [30]:
x = tf.placeholder(tf.int32, shape=(None, 3))
y = tf.placeholder(tf.int32, shape=(None, 2))

def f():
    x_r = tf.reshape(x, (-1, x.shape[1], 1))
    y_r = tf.reshape(y, (-1, 1, y.shape[1]))
    res = x_r * y_r
    print res.shape
    return res

with tf.Session() as sess:
    print(sess.run(f(), {x: [[1, 2, 3], [4, 5, 6]], y: [[10, 20], [100, 200]]}))

(?, 3, 2)
[[[  10   20]
  [  20   40]
  [  30   60]]

 [[ 400  800]
  [ 500 1000]
  [ 600 1200]]]


In [39]:
x = tf.random_uniform([2, 3, 2], maxval = 9, dtype=tf.int32)
y = tf.random_uniform([2, 1, 2], maxval = 9, dtype=tf.int32)

with tf.Session() as sess:
    z = sess.run(tf.concat((x, tf.tile(y, (1, 3, 1))), axis=2))
    print z.shape

(2, 3, 4)


In [51]:
x = tf.constant([[1., 2.], [3., 4.]])
y = tf.constant([10., 100.])
z = tf.constant([0.5])

with tf.Session() as sess:
    print sess.run(x + y)
    print sess.run((x + y) * z)

AttributeError: 'DType' object has no attribute 'type'